# Generated by Django 4.1.4 on 2025-09-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tiposabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tiposabor')),
            ],
            options={
                'verbose_name': '3 - Sabor',
                'verbose_name_plural': '3 - Sabor',
            },
        ),
    ]
