# Generated by Django 4.1.4 on 2025-09-25 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sabor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabor',
            name='nome',
            field=models.CharField(default='Sabor generico', max_length=50),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_sabor', to='myapp.tiposabor'),
        ),
    ]
