# Generated by Django 4.1.4 on 2025-09-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sabor_nome_alter_sabor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
