# Generated by Django 4.1.4 on 2025-09-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_sabor_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField()),
            ],
            options={
                'verbose_name': '4 - Cobertura',
                'verbose_name_plural': '4 - Cobertura',
            },
        ),
    ]
